name: Glossary
description: Feedback
title: "A concise description"
labels: ["glossary"]
assignees:
  - kmckenna-gleif  
body:
  - type: markdown
    attributes:
      value: | 
        2021-12-15_verifiable-LEI-(vLEI)-Ecosystem-Governance-Framework-Primary-Document-ToIP-Review_v1.0_draft.pdf
  - type: input
    id: section
    attributes:
      label: Section Name
      description: Section title from document
    validations:
      required: true
  - type: input
    id: line-number
    attributes:
      label: Line number
      description: Line number from document
    validations:
      required: true
  - type: textarea
    id: question-comment
    attributes:
      label: Question/Comment
      description: Aside from a question or comment, let us know what resolution you'd like.
    validations:
      required: true
