name: "Qualified vLEI Issuer vLEI Credential Governance Framework"
description: Feedback
title: "A concise description"
labels: ["qvi-vlei-credential-governance-framework", "identifier-and-credential-governance-framework"]
body:
  - type: markdown
    attributes:
      value: | 
        2021-12-15_Qualified-vLEI-Issuer-vLEI-Credential-GF-ToIP-Review_v1.0.draft
  - type: input
    id: section
    attributes:
      label: Section Name
      description: Section title from document
    validations:
      required: true
  - type: input
    id: row-number
    attributes:
      label: Row number
      description: Row number from document
    validations:
      required: true
  - type: textarea
    id: question-comment
    attributes:
      label: Question/Comment
      description: Aside from a question or comment, let us know what resolution you'd like.
    validations:
      required: true