name: "GLEIF Identifier Governance Framework"
description: Feedback
title: "A concise description"
labels: ["gleif-identifier-goverance-framework", "identifier-and-credential-governance-framework"]
body:
  - type: markdown
    attributes:
      value: | 
        2021-12-15_GLEIF-Identifier-GF-ToIP-Review_1.0_draft.pdf
  - type: input
    id: section
    attributes:
      label: Section Name
      description: Section title from document
    validations:
      required: true
  - type: input
    id: row-number
    attributes:
      label: Row number
      description: Row number from document
    validations:
      required: true
  - type: textarea
    id: question-comment
    attributes:
      label: Question/Comment
      description: Aside from a question or comment, let us know what resolution you'd like.
    validations:
      required: true