name: vLEI Services Catalog
description: Feedback
title: "A concise description"
labels: ["vlei-services-catalog"]
assignees:
  - kmckenna-gleif
body:
  - type: markdown
    attributes:
      value: | 
        2021-12-15_vLEI-Ecosystem-Governance-Framework-vLEI-Services-Catalog-ToIP-Review_v1.0_draft.pdf
  - type: input
    id: section
    attributes:
      label: Section Name
      description: Section title from document
    validations:
      required: true
  - type: input
    id: row-number
    attributes:
      label: Row number
      description: Row number from document
    validations:
      required: true
  - type: textarea
    id: question-comment
    attributes:
      label: Question/Comment
      description: Aside from a question or comment, let us know what resolution you'd like.
    validations:
      required: true